version: "3.9"
   
services:

  sut:
    build: .
    command: pytest
    environment:
      - DEBUG=True
      - TESTING=True 
      - FLASK_ENV=testing
    volumes:
      - .:/app
    ports:
      - "5000:5000"